[
  {
    id: 1,
    bgsound_name: 'Volume One',
    sound: 'test',
    status: '1',
    is_premium: 0,
    created_at: '2024-03-21 10:59:26',
    updated_at: '2024-04-30 10:04:08',
    deleted_at: null,
    bgsound_image: [
      {
        id: 7,
        model_type: 'App\\Models\\Bgsound',
        model_id: 1,
        uuid: '1a236276-484d-4f71-bc57-e3ee00728afa',
        collection_name: 'bgsound_bgsound_image',
        name: 'gugsali8_happy-faces_625x300_20_March_23',
        file_name: 'gugsali8_happy-faces_625x300_20_March_23.png',
        mime_type: 'image/webp',
        disk: 'public',
        conversions_disk: 'public',
        size: 149008,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 1,
        created_at: '2024-03-21T10:59:20.000000Z',
        updated_at: '2024-04-30T10:04:08.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/7/gugsali8_happy-faces_625x300_20_March_23.png',
        preview_url: '',
        url: 'https://stimuli.forebearpro.co.in/storage/app/public/7/gugsali8_happy-faces_625x300_20_March_23.png',
        thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/7/conversions/gugsali8_happy-faces_625x300_20_March_23-thumbnail.jpg',
        preview_thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/7/conversions/gugsali8_happy-faces_625x300_20_March_23-preview_thumbnail.jpg',
      },
    ],
    media: [
      {
        id: 7,
        model_type: 'App\\Models\\Bgsound',
        model_id: 1,
        uuid: '1a236276-484d-4f71-bc57-e3ee00728afa',
        collection_name: 'bgsound_bgsound_image',
        name: 'gugsali8_happy-faces_625x300_20_March_23',
        file_name: 'gugsali8_happy-faces_625x300_20_March_23.png',
        mime_type: 'image/webp',
        disk: 'public',
        conversions_disk: 'public',
        size: 149008,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 1,
        created_at: '2024-03-21T10:59:20.000000Z',
        updated_at: '2024-04-30T10:04:08.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/7/gugsali8_happy-faces_625x300_20_March_23.png',
        preview_url: '',
      },
      {
        id: 85,
        model_type: 'App\\Models\\Bgsound',
        model_id: 1,
        uuid: '6ce11fcd-4776-47ae-8e86-19154f154459',
        collection_name: 'bgsound_sound',
        name: 'backOne',
        file_name: 'backOne.mp3',
        mime_type: 'audio/mpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 7395270,
        manipulations: [],
        custom_properties: [],
        generated_conversions: [],
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T10:04:05.000000Z',
        updated_at: '2024-04-30T10:04:08.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/85/backOne.mp3',
        preview_url: '',
      },
    ],
  },
  {
    id: 2,
    bgsound_name: 'Volume Two',
    sound: 'test',
    status: '1',
    is_premium: 1,
    created_at: '2024-03-21 11:00:16',
    updated_at: '2024-04-30 10:11:59',
    deleted_at: null,
    bgsound_image: [
      {
        id: 8,
        model_type: 'App\\Models\\Bgsound',
        model_id: 2,
        uuid: 'a0c842f3-df6f-4b23-9327-1771f6845c3d',
        collection_name: 'bgsound_bgsound_image',
        name: 'hollybood1',
        file_name: 'hollybood1.jpg',
        mime_type: 'image/jpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 60927,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 1,
        created_at: '2024-03-21T11:00:10.000000Z',
        updated_at: '2024-04-30T11:58:36.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/8/hollybood1.jpg',
        preview_url: '',
        url: 'https://stimuli.forebearpro.co.in/storage/app/public/8/hollybood1.jpg',
        thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/8/conversions/hollybood1-thumbnail.jpg',
        preview_thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/8/conversions/hollybood1-preview_thumbnail.jpg',
      },
    ],
    media: [
      {
        id: 8,
        model_type: 'App\\Models\\Bgsound',
        model_id: 2,
        uuid: 'a0c842f3-df6f-4b23-9327-1771f6845c3d',
        collection_name: 'bgsound_bgsound_image',
        name: 'hollybood1',
        file_name: 'hollybood1.jpg',
        mime_type: 'image/jpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 60927,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 1,
        created_at: '2024-03-21T11:00:10.000000Z',
        updated_at: '2024-04-30T11:58:36.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/8/hollybood1.jpg',
        preview_url: '',
      },
      {
        id: 98,
        model_type: 'App\\Models\\Bgsound',
        model_id: 2,
        uuid: '0abaa826-077b-43db-8bb0-bdd785b21962',
        collection_name: 'bgsound_sound',
        name: 'BGFOUR',
        file_name: 'BGFOUR.mp3',
        mime_type: 'audio/mpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 2476452,
        manipulations: [],
        custom_properties: [],
        generated_conversions: [],
        responsive_images: [],
        order_column: 9,
        created_at: '2024-04-30T11:58:32.000000Z',
        updated_at: '2024-04-30T11:58:36.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/98/BGFOUR.mp3',
        preview_url: '',
      },
    ],
  },
  {
    id: 3,
    bgsound_name: 'Volume Three',
    sound: 'test',
    status: '1',
    is_premium: 1,
    created_at: '2024-03-21 12:07:30',
    updated_at: '2024-04-30 10:15:10',
    deleted_at: null,
    bgsound_image: [
      {
        id: 87,
        model_type: 'App\\Models\\Bgsound',
        model_id: 3,
        uuid: 'bdd0ddf2-de89-4163-b62d-893445df7ad6',
        collection_name: 'bgsound_bgsound_image',
        name: 'download (1)',
        file_name: 'download-(1).png',
        mime_type: 'image/png',
        disk: 'public',
        conversions_disk: 'public',
        size: 3323,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T10:12:54.000000Z',
        updated_at: '2024-04-30T11:56:51.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/87/download-(1).png',
        preview_url: '',
        url: 'https://stimuli.forebearpro.co.in/storage/app/public/87/download-(1).png',
        thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/87/conversions/download-(1)-thumbnail.jpg',
        preview_thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/87/conversions/download-(1)-preview_thumbnail.jpg',
      },
    ],
    media: [
      {
        id: 87,
        model_type: 'App\\Models\\Bgsound',
        model_id: 3,
        uuid: 'bdd0ddf2-de89-4163-b62d-893445df7ad6',
        collection_name: 'bgsound_bgsound_image',
        name: 'download (1)',
        file_name: 'download-(1).png',
        mime_type: 'image/png',
        disk: 'public',
        conversions_disk: 'public',
        size: 3323,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T10:12:54.000000Z',
        updated_at: '2024-04-30T11:56:51.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/87/download-(1).png',
        preview_url: '',
      },
      {
        id: 96,
        model_type: 'App\\Models\\Bgsound',
        model_id: 3,
        uuid: 'e846eb0e-1af3-4396-b86b-660f1ea39bf5',
        collection_name: 'bgsound_sound',
        name: 'BGTHREE',
        file_name: 'BGTHREE.mp3',
        mime_type: 'audio/mpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 2080557,
        manipulations: [],
        custom_properties: [],
        generated_conversions: [],
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T11:56:47.000000Z',
        updated_at: '2024-04-30T11:56:51.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/96/BGTHREE.mp3',
        preview_url: '',
      },
    ],
  },
  {
    id: 4,
    bgsound_name: 'Volume Four',
    sound: 'test',
    status: '1',
    is_premium: 1,
    created_at: '2024-04-11 11:51:07',
    updated_at: '2024-04-30 10:16:34',
    deleted_at: null,
    bgsound_image: [
      {
        id: 89,
        model_type: 'App\\Models\\Bgsound',
        model_id: 4,
        uuid: '23263219-5bd4-4116-b734-f16b19cbaa86',
        collection_name: 'bgsound_bgsound_image',
        name: 'download (8)',
        file_name: 'download-(8).jpg',
        mime_type: 'image/jpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 7819,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T10:16:19.000000Z',
        updated_at: '2024-04-30T11:55:59.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/89/download-(8).jpg',
        preview_url: '',
        url: 'https://stimuli.forebearpro.co.in/storage/app/public/89/download-(8).jpg',
        thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/89/conversions/download-(8)-thumbnail.jpg',
        preview_thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/89/conversions/download-(8)-preview_thumbnail.jpg',
      },
    ],
    media: [
      {
        id: 89,
        model_type: 'App\\Models\\Bgsound',
        model_id: 4,
        uuid: '23263219-5bd4-4116-b734-f16b19cbaa86',
        collection_name: 'bgsound_bgsound_image',
        name: 'download (8)',
        file_name: 'download-(8).jpg',
        mime_type: 'image/jpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 7819,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T10:16:19.000000Z',
        updated_at: '2024-04-30T11:55:59.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/89/download-(8).jpg',
        preview_url: '',
      },
      {
        id: 95,
        model_type: 'App\\Models\\Bgsound',
        model_id: 4,
        uuid: 'bab2889c-c248-404b-b0eb-9ee07e201f29',
        collection_name: 'bgsound_sound',
        name: 'BGTWO',
        file_name: 'BGTWO.mp3',
        mime_type: 'audio/mpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 1971975,
        manipulations: [],
        custom_properties: [],
        generated_conversions: [],
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T11:55:54.000000Z',
        updated_at: '2024-04-30T11:55:59.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/95/BGTWO.mp3',
        preview_url: '',
      },
    ],
  },
  {
    id: 8,
    bgsound_name: 'Checking Test',
    sound: null,
    status: '1',
    is_premium: 0,
    created_at: '2024-04-30 11:16:15',
    updated_at: '2024-04-30 11:16:15',
    deleted_at: null,
    bgsound_image: [
      {
        id: 92,
        model_type: 'App\\Models\\Bgsound',
        model_id: 8,
        uuid: '3fa9c8d9-a666-4c1d-88ee-a95ecf658ca5',
        collection_name: 'bgsound_bgsound_image',
        name: '[FREE - HDconvert.com] dkfk',
        file_name: '[FREE---HDconvert.com]-dkfk.png',
        mime_type: 'image/png',
        disk: 'public',
        conversions_disk: 'public',
        size: 61404,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 9,
        created_at: '2024-04-30T11:16:09.000000Z',
        updated_at: '2024-04-30T11:55:05.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/92/[FREE---HDconvert.com]-dkfk.png',
        preview_url: '',
        url: 'https://stimuli.forebearpro.co.in/storage/app/public/92/[FREE---HDconvert.com]-dkfk.png',
        thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/92/conversions/[FREE---HDconvert.com]-dkfk-thumbnail.jpg',
        preview_thumbnail:
          'https://stimuli.forebearpro.co.in/storage/app/public/92/conversions/[FREE---HDconvert.com]-dkfk-preview_thumbnail.jpg',
      },
    ],
    media: [
      {
        id: 92,
        model_type: 'App\\Models\\Bgsound',
        model_id: 8,
        uuid: '3fa9c8d9-a666-4c1d-88ee-a95ecf658ca5',
        collection_name: 'bgsound_bgsound_image',
        name: '[FREE - HDconvert.com] dkfk',
        file_name: '[FREE---HDconvert.com]-dkfk.png',
        mime_type: 'image/png',
        disk: 'public',
        conversions_disk: 'public',
        size: 61404,
        manipulations: [],
        custom_properties: [],
        generated_conversions: {thumbnail: true, preview_thumbnail: true},
        responsive_images: [],
        order_column: 9,
        created_at: '2024-04-30T11:16:09.000000Z',
        updated_at: '2024-04-30T11:55:05.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/92/[FREE---HDconvert.com]-dkfk.png',
        preview_url: '',
      },
      {
        id: 94,
        model_type: 'App\\Models\\Bgsound',
        model_id: 8,
        uuid: '62a2f22c-acf6-4b34-8134-e5bc44ee9e5d',
        collection_name: 'bgsound_sound',
        name: 'BGONE',
        file_name: 'BGONE.mp3',
        mime_type: 'audio/mpeg',
        disk: 'public',
        conversions_disk: 'public',
        size: 2269583,
        manipulations: [],
        custom_properties: [],
        generated_conversions: [],
        responsive_images: [],
        order_column: 8,
        created_at: '2024-04-30T11:54:54.000000Z',
        updated_at: '2024-04-30T11:55:05.000000Z',
        original_url:
          'https://stimuli.forebearpro.co.in/storage/app/public/94/BGONE.mp3',
        preview_url: '',
      },
    ],
  },
];
