export const vociesss= [
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-sfb-local',
    id: 'es-us-x-sfb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-PK',
    name: 'ur-PK-language',
    id: 'ur-PK-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hia-local',
    id: 'hi-in-x-hia-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-htm-network',
    id: 'ja-jp-x-htm-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-rud-local',
    id: 'ru-ru-x-rud-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'th-TH',
    name: 'th-th-x-thd-network',
    id: 'th-th-x-thd-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-yfr-network',
    id: 'nl-nl-x-yfr-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-itd-local',
    id: 'it-it-x-itd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'as-IN',
    name: 'as-in-x-end-local',
    id: 'as-in-x-end-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vif-network',
    id: 'vi-vn-x-vif-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'uk-UA',
    name: 'uk-UA-language',
    id: 'uk-UA-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-lfs-local',
    id: 'sv-se-x-lfs-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'cmn-tw-x-ctc-network',
    id: 'cmn-tw-x-ctc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-tpf-local',
    id: 'en-us-x-tpf-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-deb-network',
    id: 'de-de-x-deb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-IN',
    name: 'bn-in-x-bnd-local',
    id: 'bn-in-x-bnd-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yuf-network',
    id: 'yue-hk-x-yuf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'cy-GB',
    name: 'cy-gb-x-cyf-local',
    id: 'cy-gb-x-cyf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-yfr-local',
    id: 'nl-nl-x-yfr-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-IN',
    name: 'ur-in-x-urc-local',
    id: 'ur-in-x-urc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'cy-GB',
    name: 'cy-gb-x-cyf-network',
    id: 'cy-gb-x-cyf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-afb-local',
    id: 'pl-pl-x-afb-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-aub-network',
    id: 'en-au-x-aub-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-cab-local',
    id: 'fr-ca-x-cab-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-idd-network',
    id: 'id-id-x-idd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-idc-local',
    id: 'id-id-x-idc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-sfp-network',
    id: 'da-dk-x-sfp-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-BD',
    name: 'bn-BD-language',
    id: 'bn-BD-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-auc-local',
    id: 'en-au-x-auc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ml-IN',
    name: 'ml-in-x-mlc-local',
    id: 'ml-in-x-mlc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hr-HR',
    name: 'hr-HR-language',
    id: 'hr-HR-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-ene-network',
    id: 'en-in-x-ene-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'zh-TW-language',
    id: 'zh-TW-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mni-IN',
    name: 'mni-in-x-end-local',
    id: 'mni-in-x-end-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hie-network',
    id: 'hi-in-x-hie-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-GB-language',
    id: 'en-GB-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vid-network',
    id: 'vi-vn-x-vid-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yud-network',
    id: 'yue-hk-x-yud-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-cce-network',
    id: 'cmn-cn-x-cce-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-koc-network',
    id: 'ko-kr-x-koc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gba-network',
    id: 'en-gb-x-gba-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-bmg-network',
    id: 'pl-pl-x-bmg-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hic-network',
    id: 'hi-in-x-hic-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-aud-network',
    id: 'en-au-x-aud-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ml-IN',
    name: 'ml-IN-language',
    id: 'ml-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-sfg-network',
    id: 'en-us-x-sfg-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-zfg-network',
    id: 'pl-pl-x-zfg-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-IN-language',
    id: 'hi-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-tmc-local',
    id: 'tr-tr-x-tmc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-vlf-network',
    id: 'fr-fr-x-vlf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-ccc-local',
    id: 'cmn-cn-x-ccc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-IN',
    name: 'bn-in-x-bnc-network',
    id: 'bn-in-x-bnc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-language',
    id: 'ar-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'cmn-tw-x-ctc-local',
    id: 'cmn-tw-x-ctc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'et-EE',
    name: 'et-ee-x-tms-network',
    id: 'et-ee-x-tms-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vie-local',
    id: 'vi-vn-x-vie-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-CA-language',
    id: 'fr-CA-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hid-local',
    id: 'hi-in-x-hid-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'doi-IN',
    name: 'doi-in-x-end-local',
    id: 'doi-in-x-end-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-msc-local',
    id: 'ms-my-x-msc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-jab-network',
    id: 'ja-jp-x-jab-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-IT-language',
    id: 'it-IT-language',
  },
  {
    networkConnectionRequired: false,
    quality: 200,
    latency: 200,
    notInstalled: true,
    language: 'bs-BA',
    name: 'bs-ba-x-bsm-local',
    id: 'bs-ba-x-bsm-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'jv-ID',
    name: 'jv-id-x-jvf-local',
    id: 'jv-id-x-jvf-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-BD',
    name: 'bn-bd-x-ban-network',
    id: 'bn-bd-x-ban-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbc-network',
    id: 'en-gb-x-gbc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-BD',
    name: 'bn-bd-x-ban-local',
    id: 'bn-bd-x-ban-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-ard-network',
    id: 'ar-xa-x-ard-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hr-HR',
    name: 'hr-hr-x-hra-local',
    id: 'hr-hr-x-hra-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-ssa-network',
    id: 'cmn-cn-x-ssa-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'el-GR',
    name: 'el-GR-language',
    id: 'el-GR-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sat-IN',
    name: 'sat-IN-language',
    id: 'sat-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-sfg-local',
    id: 'en-us-x-sfg-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-PH-language',
    id: 'fil-PH-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-jmk-network',
    id: 'pl-pl-x-jmk-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-rue-network',
    id: 'ru-ru-x-rue-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-IN',
    name: 'bn-IN-language',
    id: 'bn-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hia-network',
    id: 'hi-in-x-hia-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-esc-local',
    id: 'es-us-x-esc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fi-FI',
    name: 'fi-FI-language',
    id: 'fi-FI-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-cab-network',
    id: 'fr-ca-x-cab-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hu-HU',
    name: 'hu-HU-language',
    id: 'hu-HU-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-FR-language',
    id: 'fr-FR-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-fie-local',
    id: 'fil-ph-x-fie-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-DK-language',
    id: 'da-DK-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-jad-network',
    id: 'ja-jp-x-jad-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-afp-local',
    id: 'sv-se-x-afp-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-fid-network',
    id: 'fil-ph-x-fid-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ml-IN',
    name: 'ml-in-x-mlc-network',
    id: 'ml-in-x-mlc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kn-IN',
    name: 'kn-in-x-knc-local',
    id: 'kn-in-x-knc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'si-LK',
    name: 'si-lk-x-sin-local',
    id: 'si-lk-x-sin-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sk-SK',
    name: 'sk-sk-x-sfk-local',
    id: 'sk-sk-x-sfk-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iob-local',
    id: 'en-us-x-iob-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bg-BG',
    name: 'bg-bg-x-ifk-local',
    id: 'bg-bg-x-ifk-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-ccc-network',
    id: 'cmn-cn-x-ccc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'th-TH',
    name: 'th-th-x-thd-local',
    id: 'th-th-x-thd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'km-KH',
    name: 'km-KH-language',
    id: 'km-KH-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-heb-network',
    id: 'he-il-x-heb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bs-BA',
    name: 'bs-ba-language',
    id: 'bs-ba-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-in-x-mra-network',
    id: 'mr-in-x-mra-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-esf-local',
    id: 'es-us-x-esf-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kn-IN',
    name: 'kn-in-x-knd-network',
    id: 'kn-in-x-knd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pac-local',
    id: 'pa-in-x-pac-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-are-local',
    id: 'ar-xa-x-are-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-in-x-mrd-local',
    id: 'mr-in-x-mrd-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hu-HU',
    name: 'hu-hu-x-kfl-network',
    id: 'hu-hu-x-kfl-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-jmn-network',
    id: 'pt-pt-x-jmn-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-lfc-network',
    id: 'nl-nl-x-lfc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-frc-network',
    id: 'fr-fr-x-frc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-dma-network',
    id: 'nl-nl-x-dma-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'cs-CZ',
    name: 'cs-cz-x-jfs-local',
    id: 'cs-cz-x-jfs-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-efu-network',
    id: 'tr-tr-x-efu-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'et-EE',
    name: 'et-ee-x-tms-local',
    id: 'et-ee-x-tms-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-enc-network',
    id: 'en-in-x-enc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hr-HR',
    name: 'hr-hr-x-hrb-network',
    id: 'hr-hr-x-hrb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eef-local',
    id: 'es-es-x-eef-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbc-local',
    id: 'en-gb-x-gbc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eec-local',
    id: 'es-es-x-eec-local',
  },
  {
    networkConnectionRequired: false,
    quality: 200,
    latency: 200,
    notInstalled: true,
    language: 'sw-KE',
    name: 'sw-ke-x-swm-local',
    id: 'sw-ke-x-swm-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-mfm-local',
    id: 'tr-tr-x-mfm-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'gu-IN',
    name: 'gu-in-x-gum-network',
    id: 'gu-in-x-gum-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'is-IS',
    name: 'is-is-x-isf-local',
    id: 'is-is-x-isf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-enc-local',
    id: 'en-in-x-enc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-dmc-local',
    id: 'sv-se-x-dmc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-IN',
    name: 'ur-in-x-urc-network',
    id: 'ur-in-x-urc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-msg-network',
    id: 'ms-my-x-msg-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fi-FI',
    name: 'fi-fi-x-afi-local',
    id: 'fi-fi-x-afi-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ca-ES',
    name: 'ca-ES-language',
    id: 'ca-ES-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-tpd-network',
    id: 'en-us-x-tpd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-cfl-local',
    id: 'nb-no-x-cfl-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-kod-local',
    id: 'ko-kr-x-kod-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ta-IN',
    name: 'ta-IN-language',
    id: 'ta-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'is-IS',
    name: 'is-is-x-isf-network',
    id: 'is-is-x-isf-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-esf-network',
    id: 'es-us-x-esf-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-jar-network',
    id: 'yue-hk-x-jar-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sr-RS',
    name: 'sr-rs-x-gfg-network',
    id: 'sr-rs-x-gfg-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-tpc-network',
    id: 'en-us-x-tpc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-gft-network',
    id: 'vi-vn-x-gft-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-frb-local',
    id: 'fr-fr-x-frb-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-hee-network',
    id: 'he-il-x-hee-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'el-GR',
    name: 'el-gr-x-vfz-local',
    id: 'el-gr-x-vfz-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-afb-network',
    id: 'pl-pl-x-afb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-end-local',
    id: 'en-in-x-end-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-PT-language',
    id: 'pt-PT-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-jad-local',
    id: 'ja-jp-x-jad-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-dmc-network',
    id: 'sv-se-x-dmc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-arc-local',
    id: 'ar-xa-x-arc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'gu-IN',
    name: 'gu-in-x-guf-network',
    id: 'gu-in-x-guf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-ism-local',
    id: 'ko-kr-x-ism-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'gu-IN',
    name: 'gu-IN-language',
    id: 'gu-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-ena-network',
    id: 'en-in-x-ena-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'or-IN',
    name: 'or-IN-language',
    id: 'or-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'or-IN',
    name: 'or-in-x-end-local',
    id: 'or-in-x-end-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-br-x-pte-local',
    id: 'pt-br-x-pte-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eed-local',
    id: 'es-es-x-eed-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-hec-network',
    id: 'he-il-x-hec-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-rfj-network',
    id: 'nb-no-x-rfj-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-DE-language',
    id: 'de-DE-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-BE',
    name: 'nl-be-x-bed-network',
    id: 'nl-be-x-bed-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-msg-local',
    id: 'ms-my-x-msg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-frd-network',
    id: 'fr-fr-x-frd-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bg-BG',
    name: 'bg-bg-x-ifk-network',
    id: 'bg-bg-x-ifk-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-idd-local',
    id: 'id-id-x-idd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yuf-local',
    id: 'yue-hk-x-yuf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'brx-IN',
    name: 'brx-IN-language',
    id: 'brx-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-JP-language',
    id: 'ja-JP-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-aub-local',
    id: 'en-au-x-aub-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-ES-language',
    id: 'es-ES-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'gu-IN',
    name: 'gu-in-x-guf-local',
    id: 'gu-in-x-guf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-jmk-local',
    id: 'pl-pl-x-jmk-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-MY-language',
    id: 'ms-MY-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-fid-local',
    id: 'fil-ph-x-fid-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-BE',
    name: 'nl-be-x-bec-network',
    id: 'nl-be-x-bec-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-fie-network',
    id: 'fil-ph-x-fie-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-in-x-mrc-local',
    id: 'mr-in-x-mrc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-ard-local',
    id: 'ar-xa-x-ard-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-jar-local',
    id: 'yue-hk-x-jar-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yue-local',
    id: 'yue-hk-x-yue-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'su-ID',
    name: 'su-id-x-suf-network',
    id: 'su-id-x-suf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'te-IN',
    name: 'te-in-x-teg-local',
    id: 'te-in-x-teg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-cfl-network',
    id: 'nb-no-x-cfl-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbb-local',
    id: 'en-gb-x-gbb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-itb-local',
    id: 'it-it-x-itb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'su-ID',
    name: 'su-ID-language',
    id: 'su-ID-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'th-TH',
    name: 'th-TH-language',
    id: 'th-TH-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'zh-CN-language',
    id: 'zh-CN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-RU-language',
    id: 'ru-RU-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iob-network',
    id: 'en-us-x-iob-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-cmj-network',
    id: 'nb-no-x-cmj-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-AU-language',
    id: 'en-AU-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iol-network',
    id: 'en-us-x-iol-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-arz-local',
    id: 'ar-xa-x-arz-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-zfg-local',
    id: 'pl-pl-x-zfg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-ruc-network',
    id: 'ru-ru-x-ruc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-BR-language',
    id: 'pt-BR-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-rue-local',
    id: 'ru-ru-x-rue-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pag-local',
    id: 'pa-in-x-pag-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-dfz-network',
    id: 'id-id-x-dfz-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-IN-language',
    id: 'pa-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iom-network',
    id: 'en-us-x-iom-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-lfc-local',
    id: 'nl-nl-x-lfc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-dfz-local',
    id: 'id-id-x-dfz-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ks-IN',
    name: 'ks-IN-language',
    id: 'ks-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'doi-IN',
    name: 'doi-IN-language',
    id: 'doi-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'lv-LV',
    name: 'lv-LV-language',
    id: 'lv-LV-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-cac-local',
    id: 'fr-ca-x-cac-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-tmc-network',
    id: 'tr-tr-x-tmc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-jfb-network',
    id: 'pt-pt-x-jfb-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-kda-network',
    id: 'it-it-x-kda-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-fra-local',
    id: 'fr-fr-x-fra-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-kob-network',
    id: 'ko-kr-x-kob-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-IN-language',
    id: 'mr-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-hed-network',
    id: 'he-il-x-hed-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-efu-local',
    id: 'tr-tr-x-efu-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-tfs-local',
    id: 'nb-no-x-tfs-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'jv-ID',
    name: 'jv-id-x-jvf-network',
    id: 'jv-id-x-jvf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'et-EE',
    name: 'et-EE-language',
    id: 'et-EE-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-KR-language',
    id: 'ko-KR-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-br-x-afs-local',
    id: 'pt-br-x-afs-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-idc-network',
    id: 'id-id-x-idc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-NG',
    name: 'en-NG-language',
    id: 'en-NG-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'te-IN',
    name: 'te-IN-language',
    id: 'te-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'th-TH',
    name: 'th-th-x-thc-local',
    id: 'th-th-x-thc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-jac-local',
    id: 'ja-jp-x-jac-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-dea-network',
    id: 'de-de-x-dea-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'cmn-tw-x-ctd-network',
    id: 'cmn-tw-x-ctd-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hid-network',
    id: 'hi-in-x-hid-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-hee-local',
    id: 'he-il-x-hee-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ca-ES',
    name: 'ca-es-x-caf-network',
    id: 'ca-es-x-caf-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vie-network',
    id: 'vi-vn-x-vie-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-nmm-network',
    id: 'da-dk-x-nmm-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-cfs-local',
    id: 'tr-tr-x-cfs-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eee-local',
    id: 'es-es-x-eee-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbd-local',
    id: 'en-gb-x-gbd-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-oda-network',
    id: 'pl-pl-x-oda-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbg-local',
    id: 'en-gb-x-gbg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-in-x-mrd-network',
    id: 'mr-in-x-mrd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-rjs-local',
    id: 'en-gb-x-rjs-local',
  },
  {
    networkConnectionRequired: true,
    quality: 200,
    latency: 200,
    notInstalled: true,
    language: 'sq-AL',
    name: 'sq-al-x-sqm-network',
    id: 'sq-al-x-sqm-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iom-local',
    id: 'en-us-x-iom-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-auc-network',
    id: 'en-au-x-auc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-kda-local',
    id: 'it-it-x-kda-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'th-TH',
    name: 'th-th-x-thc-network',
    id: 'th-th-x-thc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-fic-local',
    id: 'fil-ph-x-fic-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-kod-network',
    id: 'ko-kr-x-kod-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-IN',
    name: 'bn-in-x-bnd-network',
    id: 'bn-in-x-bnd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-sfs-local',
    id: 'pt-pt-x-sfs-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-ssa-local',
    id: 'cmn-cn-x-ssa-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'si-LK',
    name: 'si-lk-x-sin-network',
    id: 'si-lk-x-sin-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-caa-network',
    id: 'fr-ca-x-caa-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-ID-language',
    id: 'id-ID-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-end-network',
    id: 'en-in-x-end-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pag-network',
    id: 'pa-in-x-pag-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-gft-local',
    id: 'vi-vn-x-gft-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mai-IN',
    name: 'mai-in-x-end-local',
    id: 'mai-in-x-end-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hr-HR',
    name: 'hr-hr-x-hra-network',
    id: 'hr-hr-x-hra-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'lt-LT',
    name: 'lt-lt-language',
    id: 'lt-lt-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-NG',
    name: 'en-ng-x-tfn-network',
    id: 'en-ng-x-tfn-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-ama-network',
    id: 'tr-tr-x-ama-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sa-IN',
    name: 'sa-IN-language',
    id: 'sa-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-nmm-local',
    id: 'da-dk-x-nmm-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-vfb-network',
    id: 'da-dk-x-vfb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-oda-local',
    id: 'pl-pl-x-oda-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-afp-network',
    id: 'sv-se-x-afp-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-TR-language',
    id: 'tr-TR-language',
  },
  {
    networkConnectionRequired: true,
    quality: 200,
    latency: 200,
    notInstalled: true,
    language: 'sw-KE',
    name: 'sw-ke-x-swm-network',
    id: 'sw-ke-x-swm-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-koc-local',
    id: 'ko-kr-x-koc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-esd-local',
    id: 'es-us-x-esd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-US-language',
    id: 'en-US-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'lt-LT',
    name: 'lt-lt-x-amc-network',
    id: 'lt-lt-x-amc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-kfm-network',
    id: 'da-dk-x-kfm-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sq-AL',
    name: 'sq-al-language',
    id: 'sq-al-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-frc-local',
    id: 'fr-fr-x-frc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'su-ID',
    name: 'su-id-x-suf-local',
    id: 'su-id-x-suf-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-sfb-network',
    id: 'es-us-x-sfb-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-rud-network',
    id: 'ru-ru-x-rud-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gba-local',
    id: 'en-gb-x-gba-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kn-IN',
    name: 'kn-in-x-knd-local',
    id: 'kn-in-x-knd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sd-IN',
    name: 'sd-IN-language',
    id: 'sd-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-ene-local',
    id: 'en-in-x-ene-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pae-local',
    id: 'pa-in-x-pae-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-HK-language',
    id: 'yue-HK-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-aua-network',
    id: 'en-au-x-aua-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sat-IN',
    name: 'sat-in-x-end-local',
    id: 'sat-in-x-end-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-ide-network',
    id: 'id-id-x-ide-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-htm-local',
    id: 'ja-jp-x-htm-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-ruf-local',
    id: 'ru-ru-x-ruf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-NG',
    name: 'en-ng-x-tfn-local',
    id: 'en-ng-x-tfn-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-jac-network',
    id: 'ja-jp-x-jac-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-cfg-local',
    id: 'sv-se-x-cfg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-IN',
    name: 'ur-in-x-urb-network',
    id: 'ur-in-x-urb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hic-local',
    id: 'hi-in-x-hic-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-cmh-network',
    id: 'sv-se-x-cmh-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'brx-IN',
    name: 'brx-in-x-end-local',
    id: 'brx-in-x-end-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ml-IN',
    name: 'ml-in-x-mle-local',
    id: 'ml-in-x-mle-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-br-x-ptd-local',
    id: 'pt-br-x-ptd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-kfm-local',
    id: 'da-dk-x-kfm-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-tpd-local',
    id: 'en-us-x-tpd-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ro-RO',
    name: 'ro-ro-x-vfv-network',
    id: 'ro-ro-x-vfv-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'id-ID',
    name: 'id-id-x-ide-local',
    id: 'id-id-x-ide-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-ccd-network',
    id: 'cmn-cn-x-ccd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mni-IN',
    name: 'mni-IN-language',
    id: 'mni-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-NO-language',
    id: 'nb-NO-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-caa-local',
    id: 'fr-ca-x-caa-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-PK',
    name: 'ur-pk-x-cfn-local',
    id: 'ur-pk-x-cfn-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hu-HU',
    name: 'hu-hu-x-kfl-local',
    id: 'hu-hu-x-kfl-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-cad-local',
    id: 'fr-ca-x-cad-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yuc-network',
    id: 'yue-hk-x-yuc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-VN-language',
    id: 'vi-VN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vif-local',
    id: 'vi-vn-x-vif-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'is-IS',
    name: 'is-is-language',
    id: 'is-is-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-pmj-local',
    id: 'pt-pt-x-pmj-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-tfb-network',
    id: 'nl-nl-x-tfb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-aua-local',
    id: 'en-au-x-aua-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-rfj-local',
    id: 'nb-no-x-rfj-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-cac-network',
    id: 'fr-ca-x-cac-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-rjs-network',
    id: 'en-gb-x-rjs-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-ruc-local',
    id: 'ru-ru-x-ruc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-ruf-network',
    id: 'ru-ru-x-ruf-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-heb-local',
    id: 'he-il-x-heb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ks-IN',
    name: 'ks-in-x-end-local',
    id: 'ks-in-x-end-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-sfs-network',
    id: 'pt-pt-x-sfs-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-fic-network',
    id: 'fil-ph-x-fic-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eea-network',
    id: 'es-es-x-eea-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-IN',
    name: 'ur-in-x-urb-local',
    id: 'ur-in-x-urb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-dfc-local',
    id: 'ru-ru-x-dfc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-cfc-network',
    id: 'fil-ph-x-cfc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kok-IN',
    name: 'kok-in-x-end-local',
    id: 'kok-in-x-end-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'cs-CZ',
    name: 'cs-cz-x-jfs-network',
    id: 'cs-cz-x-jfs-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-itc-local',
    id: 'it-it-x-itc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bn-IN',
    name: 'bn-in-x-bnc-local',
    id: 'bn-in-x-bnc-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-deg-network',
    id: 'de-de-x-deg-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pac-network',
    id: 'pa-in-x-pac-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ro-RO',
    name: 'ro-RO-language',
    id: 'ro-RO-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'uk-UA',
    name: 'uk-ua-x-hfd-local',
    id: 'uk-ua-x-hfd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-BE',
    name: 'nl-be-x-bec-local',
    id: 'nl-be-x-bec-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yud-local',
    id: 'yue-hk-x-yud-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-mse-network',
    id: 'ms-my-x-mse-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-PL-language',
    id: 'pl-PL-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-are-network',
    id: 'ar-xa-x-are-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vic-network',
    id: 'vi-vn-x-vic-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-language',
    id: 'he-il-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vic-local',
    id: 'vi-vn-x-vic-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sa-IN',
    name: 'sa-in-x-end-local',
    id: 'sa-in-x-end-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sr-RS',
    name: 'sr-rs-language',
    id: 'sr-rs-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-AU',
    name: 'en-au-x-aud-local',
    id: 'en-au-x-aud-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbb-network',
    id: 'en-gb-x-gbb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ne-NP',
    name: 'ne-np-x-nep-local',
    id: 'ne-np-x-nep-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fil-PH',
    name: 'fil-ph-x-cfc-local',
    id: 'fil-ph-x-cfc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'cmn-tw-x-cte-local',
    id: 'cmn-tw-x-cte-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ne-NP',
    name: 'ne-np-x-nep-network',
    id: 'ne-np-x-nep-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iog-network',
    id: 'en-us-x-iog-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ne-NP',
    name: 'ne-NP-language',
    id: 'ne-NP-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-deb-local',
    id: 'de-de-x-deb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-BE',
    name: 'nl-BE-language',
    id: 'nl-BE-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'km-KH',
    name: 'km-kh-x-khm-network',
    id: 'km-kh-x-khm-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-IN',
    name: 'ur-IN-language',
    id: 'ur-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'si-LK',
    name: 'si-LK-language',
    id: 'si-LK-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sk-SK',
    name: 'sk-sk-x-sfk-network',
    id: 'sk-sk-x-sfk-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-br-x-pte-network',
    id: 'pt-br-x-pte-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-cfg-network',
    id: 'sv-se-x-cfg-network',
  },
  {
    networkConnectionRequired: true,
    quality: 200,
    latency: 200,
    notInstalled: true,
    language: 'bs-BA',
    name: 'bs-ba-x-bsm-network',
    id: 'bs-ba-x-bsm-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fi-FI',
    name: 'fi-fi-x-afi-network',
    id: 'fi-fi-x-afi-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yuc-local',
    id: 'yue-hk-x-yuc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'lv-LV',
    name: 'lv-lv-x-imr-local',
    id: 'lv-lv-x-imr-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-itc-network',
    id: 'it-it-x-itc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sk-SK',
    name: 'sk-SK-language',
    id: 'sk-SK-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'uk-UA',
    name: 'uk-ua-x-hfd-network',
    id: 'uk-ua-x-hfd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-ccd-local',
    id: 'cmn-cn-x-ccd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-msd-local',
    id: 'ms-my-x-msd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-ama-local',
    id: 'tr-tr-x-ama-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'vi-VN',
    name: 'vi-vn-x-vid-local',
    id: 'vi-vn-x-vid-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'te-IN',
    name: 'te-in-x-teg-network',
    id: 'te-in-x-teg-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-frb-network',
    id: 'fr-fr-x-frb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'te-IN',
    name: 'te-in-x-tee-local',
    id: 'te-in-x-tee-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-tfb-local',
    id: 'nl-nl-x-tfb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'hi-IN',
    name: 'hi-in-x-hie-local',
    id: 'hi-in-x-hie-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-jfb-local',
    id: 'pt-pt-x-jfb-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbg-network',
    id: 'en-gb-x-gbg-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sl-SI',
    name: 'sl-si-x-frm-local',
    id: 'sl-si-x-frm-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-cmh-local',
    id: 'sv-se-x-cmh-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-in-x-mra-local',
    id: 'mr-in-x-mra-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-itb-network',
    id: 'it-it-x-itb-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-vfb-local',
    id: 'da-dk-x-vfb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ta-IN',
    name: 'ta-in-x-tad-local',
    id: 'ta-in-x-tad-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-pmj-network',
    id: 'pt-pt-x-pmj-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-esd-network',
    id: 'es-us-x-esd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-tmg-local',
    id: 'nb-no-x-tmg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ru-RU',
    name: 'ru-ru-x-dfc-network',
    id: 'ru-ru-x-dfc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mai-IN',
    name: 'mai-IN-language',
    id: 'mai-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-deg-local',
    id: 'de-de-x-deg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-CA',
    name: 'fr-ca-x-cad-network',
    id: 'fr-ca-x-cad-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'el-GR',
    name: 'el-gr-x-vfz-network',
    id: 'el-gr-x-vfz-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-bmh-network',
    id: 'nl-nl-x-bmh-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-hed-local',
    id: 'he-il-x-hed-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-tpf-network',
    id: 'en-us-x-tpf-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'en-GB',
    name: 'en-gb-x-gbd-network',
    id: 'en-gb-x-gbd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'hr-HR',
    name: 'hr-hr-x-hrb-local',
    id: 'hr-hr-x-hrb-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-in-x-ena-local',
    id: 'en-in-x-ena-local',
  },
  {
    networkConnectionRequired: false,
    quality: 200,
    latency: 200,
    notInstalled: true,
    language: 'sq-AL',
    name: 'sq-al-x-sqm-local',
    id: 'sq-al-x-sqm-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kn-IN',
    name: 'kn-in-x-knc-network',
    id: 'kn-in-x-knc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-tfs-network',
    id: 'nb-no-x-tfs-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ca-ES',
    name: 'ca-es-x-caf-local',
    id: 'ca-es-x-caf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-nfh-local',
    id: 'de-de-x-nfh-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kn-IN',
    name: 'kn-IN-language',
    id: 'kn-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sd-IN',
    name: 'sd-in-x-end-local',
    id: 'sd-in-x-end-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eea-local',
    id: 'es-es-x-eea-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-msd-network',
    id: 'ms-my-x-msd-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'te-IN',
    name: 'te-in-x-tee-network',
    id: 'te-in-x-tee-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-fra-network',
    id: 'fr-fr-x-fra-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pad-network',
    id: 'pa-in-x-pad-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-se-x-lfs-network',
    id: 'sv-se-x-lfs-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-br-x-ptd-network',
    id: 'pt-br-x-ptd-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ur-PK',
    name: 'ur-pk-x-cfn-network',
    id: 'ur-pk-x-cfn-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ta-IN',
    name: 'ta-in-x-tac-local',
    id: 'ta-in-x-tac-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eec-network',
    id: 'es-es-x-eec-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-PT',
    name: 'pt-pt-x-jmn-local',
    id: 'pt-pt-x-jmn-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'da-DK',
    name: 'da-dk-x-sfp-local',
    id: 'da-dk-x-sfp-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-cfs-network',
    id: 'tr-tr-x-cfs-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pae-network',
    id: 'pa-in-x-pae-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-msc-network',
    id: 'ms-my-x-msc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'gu-IN',
    name: 'gu-in-x-gum-local',
    id: 'gu-in-x-gum-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-us-x-esc-network',
    id: 'es-us-x-esc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-BE',
    name: 'nl-be-x-bed-local',
    id: 'nl-be-x-bed-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'lt-LT',
    name: 'lt-lt-x-amc-local',
    id: 'lt-lt-x-amc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'km-KH',
    name: 'km-kh-x-khm-local',
    id: 'km-kh-x-khm-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-bmh-local',
    id: 'nl-nl-x-bmh-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'he-IL',
    name: 'he-il-x-hec-local',
    id: 'he-il-x-hec-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-cmj-local',
    id: 'nb-no-x-cmj-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-kob-local',
    id: 'ko-kr-x-kob-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ta-IN',
    name: 'ta-in-x-tac-network',
    id: 'ta-in-x-tac-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-vlf-local',
    id: 'fr-fr-x-vlf-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iog-local',
    id: 'en-us-x-iog-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'cmn-tw-x-ctd-local',
    id: 'cmn-tw-x-ctd-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-arz-network',
    id: 'ar-xa-x-arz-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'bg-BG',
    name: 'bg-bg-language',
    id: 'bg-bg-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ar',
    name: 'ar-xa-x-arc-network',
    id: 'ar-xa-x-arc-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-nfh-network',
    id: 'de-de-x-nfh-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pl-PL',
    name: 'pl-pl-x-bmg-local',
    id: 'pl-pl-x-bmg-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ko-KR',
    name: 'ko-kr-x-ism-network',
    id: 'ko-kr-x-ism-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'cy-GB',
    name: 'cy-GB-language',
    id: 'cy-GB-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'cs-CZ',
    name: 'cs-CZ-language',
    id: 'cs-CZ-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'fr-FR',
    name: 'fr-fr-x-frd-local',
    id: 'fr-fr-x-frd-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pa-IN',
    name: 'pa-in-x-pad-local',
    id: 'pa-in-x-pad-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'jv-ID',
    name: 'jv-ID-language',
    id: 'jv-ID-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'de-DE',
    name: 'de-de-x-dea-local',
    id: 'de-de-x-dea-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'kok-IN',
    name: 'kok-IN-language',
    id: 'kok-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'pt-BR',
    name: 'pt-br-x-afs-network',
    id: 'pt-br-x-afs-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'mr-IN',
    name: 'mr-in-x-mrc-network',
    id: 'mr-in-x-mrc-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-NL-language',
    id: 'nl-NL-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nb-NO',
    name: 'nb-no-x-tmg-network',
    id: 'nb-no-x-tmg-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ja-JP',
    name: 'ja-jp-x-jab-local',
    id: 'ja-jp-x-jab-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-tpc-local',
    id: 'en-us-x-tpc-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ro-RO',
    name: 'ro-ro-x-vfv-local',
    id: 'ro-ro-x-vfv-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'tr-TR',
    name: 'tr-tr-x-mfm-network',
    id: 'tr-tr-x-mfm-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-ES',
    name: 'es-es-x-eed-network',
    id: 'es-es-x-eed-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-IN',
    name: 'en-IN-language',
    id: 'en-IN-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sw-KE',
    name: 'sw-ke-language',
    id: 'sw-ke-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sl-SI',
    name: 'sl-SI-language',
    id: 'sl-SI-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ms-MY',
    name: 'ms-my-x-mse-local',
    id: 'ms-my-x-mse-local',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'es-US',
    name: 'es-US-language',
    id: 'es-US-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'sv-SE',
    name: 'sv-SE-language',
    id: 'sv-SE-language',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-CN',
    name: 'cmn-cn-x-cce-local',
    id: 'cmn-cn-x-cce-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'zh-TW',
    name: 'cmn-tw-x-cte-network',
    id: 'cmn-tw-x-cte-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'it-IT',
    name: 'it-it-x-itd-network',
    id: 'it-it-x-itd-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'as-IN',
    name: 'as-IN-language',
    id: 'as-IN-language',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ml-IN',
    name: 'ml-in-x-mle-network',
    id: 'ml-in-x-mle-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'nl-NL',
    name: 'nl-nl-x-dma-local',
    id: 'nl-nl-x-dma-local',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'ta-IN',
    name: 'ta-in-x-tad-network',
    id: 'ta-in-x-tad-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'yue-HK',
    name: 'yue-hk-x-yue-network',
    id: 'yue-hk-x-yue-network',
  },
  {
    networkConnectionRequired: true,
    quality: 400,
    latency: 200,
    notInstalled: true,
    language: 'lv-LV',
    name: 'lv-lv-x-imr-network',
    id: 'lv-lv-x-imr-network',
  },
  {
    networkConnectionRequired: false,
    quality: 400,
    latency: 200,
    notInstalled: false,
    language: 'en-US',
    name: 'en-us-x-iol-local',
    id: 'en-us-x-iol-local',
  },
];
