const thisdata = {
  status: true,
  data: {
    playlists: [],
    categories: [
      {
        id: 2,
        categories_name: 'Billionaire Mindset',
        status: '1',
        created_at: '2024-03-21 10:27:08',
        updated_at: '2024-03-21 10:27:08',
        deleted_at: null,
        is_favorite: true,
        favorite_id: 31,
        categories_image: [],
        media: [],
      },
      {
        id: 3,
        categories_name: 'Change your beliefs About',
        status: '1',
        created_at: '2024-03-21 10:30:19',
        updated_at: '2024-03-21 10:30:19',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 3,
            model_type: 'App\\Models\\Category',
            model_id: 3,
            uuid: 'bee51744-ba24-4106-9e0a-66ebd3feff8f',
            collection_name: 'category_categories_image',
            name: 'download (8)',
            file_name: 'download-(8).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 7819,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:30:14.000000Z',
            updated_at: '2024-03-21T10:30:19.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/3/download-(8).jpg',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/3/download-(8).jpg',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/3/conversions/download-(8)-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/3/conversions/download-(8)-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 3,
            model_type: 'App\\Models\\Category',
            model_id: 3,
            uuid: 'bee51744-ba24-4106-9e0a-66ebd3feff8f',
            collection_name: 'category_categories_image',
            name: 'download (8)',
            file_name: 'download-(8).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 7819,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:30:14.000000Z',
            updated_at: '2024-03-21T10:30:19.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/3/download-(8).jpg',
            preview_url: '',
          },
        ],
      },
      {
        id: 4,
        categories_name: 'Debt Management',
        status: '1',
        created_at: '2024-03-21 10:31:26',
        updated_at: '2024-03-21 10:31:26',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 4,
            model_type: 'App\\Models\\Category',
            model_id: 4,
            uuid: '797bb8e2-45e6-4790-b384-a53595706449',
            collection_name: 'category_categories_image',
            name: 'download (9)',
            file_name: 'download-(9).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 9396,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:31:22.000000Z',
            updated_at: '2024-03-21T10:31:26.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/4/download-(9).jpg',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/4/download-(9).jpg',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/4/conversions/download-(9)-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/4/conversions/download-(9)-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 4,
            model_type: 'App\\Models\\Category',
            model_id: 4,
            uuid: '797bb8e2-45e6-4790-b384-a53595706449',
            collection_name: 'category_categories_image',
            name: 'download (9)',
            file_name: 'download-(9).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 9396,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:31:22.000000Z',
            updated_at: '2024-03-21T10:31:26.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/4/download-(9).jpg',
            preview_url: '',
          },
        ],
      },
      {
        id: 5,
        categories_name: 'Get Out of Debt',
        status: '1',
        created_at: '2024-03-21 10:34:01',
        updated_at: '2024-03-21 10:34:01',
        deleted_at: null,
        is_favorite: true,
        favorite_id: 6,
        categories_image: [
          {
            id: 5,
            model_type: 'App\\Models\\Category',
            model_id: 5,
            uuid: '83ea12ab-f709-4348-bfe9-d39a4bd28c22',
            collection_name: 'category_categories_image',
            name: 'download (10)',
            file_name: 'download-(10).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 8101,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:33:58.000000Z',
            updated_at: '2024-03-21T10:34:01.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/5/download-(10).jpg',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/5/download-(10).jpg',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/5/conversions/download-(10)-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/5/conversions/download-(10)-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 5,
            model_type: 'App\\Models\\Category',
            model_id: 5,
            uuid: '83ea12ab-f709-4348-bfe9-d39a4bd28c22',
            collection_name: 'category_categories_image',
            name: 'download (10)',
            file_name: 'download-(10).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 8101,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:33:58.000000Z',
            updated_at: '2024-03-21T10:34:01.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/5/download-(10).jpg',
            preview_url: '',
          },
        ],
      },
      {
        id: 6,
        categories_name: 'Manifest Wealth  ',
        status: '1',
        created_at: '2024-03-21 10:35:55',
        updated_at: '2024-03-21 10:35:55',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 6,
            model_type: 'App\\Models\\Category',
            model_id: 6,
            uuid: '3c41a21b-ae17-4065-86a6-6c14f2834850',
            collection_name: 'category_categories_image',
            name: 'images (2)',
            file_name: 'images-(2).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 7690,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:35:51.000000Z',
            updated_at: '2024-03-21T10:49:54.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/6/images-(2).jpg',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/6/images-(2).jpg',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/6/conversions/images-(2)-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/6/conversions/images-(2)-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 6,
            model_type: 'App\\Models\\Category',
            model_id: 6,
            uuid: '3c41a21b-ae17-4065-86a6-6c14f2834850',
            collection_name: 'category_categories_image',
            name: 'images (2)',
            file_name: 'images-(2).jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 7690,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 1,
            created_at: '2024-03-21T10:35:51.000000Z',
            updated_at: '2024-03-21T10:49:54.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/6/images-(2).jpg',
            preview_url: '',
          },
        ],
      },
      {
        id: 7,
        categories_name: 'Gynecologists',
        status: '1',
        created_at: '2024-03-27 14:51:29',
        updated_at: '2024-03-27 15:01:55',
        deleted_at: null,
        is_favorite: true,
        favorite_id: 22,
        categories_image: [],
        media: [],
      },
      {
        id: 8,
        categories_name: 'test',
        status: '1',
        created_at: '2024-03-28 07:50:24',
        updated_at: '2024-03-28 07:50:24',
        deleted_at: null,
        is_favorite: true,
        favorite_id: 13,
        categories_image: [
          {
            id: 32,
            model_type: 'App\\Models\\Category',
            model_id: 8,
            uuid: 'fb86b99d-59a6-45b3-b5d2-4f5c8c136215',
            collection_name: 'category_categories_image',
            name: '[FREE - HDconvert.com] dkfk',
            file_name: '[FREE---HDconvert.com]-dkfk.png',
            mime_type: 'image/png',
            disk: 'public',
            conversions_disk: 'public',
            size: 61404,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 20,
            created_at: '2024-03-28T07:50:04.000000Z',
            updated_at: '2024-03-28T07:50:24.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/32/[FREE---HDconvert.com]-dkfk.png',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/32/[FREE---HDconvert.com]-dkfk.png',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/32/conversions/[FREE---HDconvert.com]-dkfk-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/32/conversions/[FREE---HDconvert.com]-dkfk-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 32,
            model_type: 'App\\Models\\Category',
            model_id: 8,
            uuid: 'fb86b99d-59a6-45b3-b5d2-4f5c8c136215',
            collection_name: 'category_categories_image',
            name: '[FREE - HDconvert.com] dkfk',
            file_name: '[FREE---HDconvert.com]-dkfk.png',
            mime_type: 'image/png',
            disk: 'public',
            conversions_disk: 'public',
            size: 61404,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 20,
            created_at: '2024-03-28T07:50:04.000000Z',
            updated_at: '2024-03-28T07:50:24.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/32/[FREE---HDconvert.com]-dkfk.png',
            preview_url: '',
          },
        ],
      },
      {
        id: 9,
        categories_name: 'test',
        status: '1',
        created_at: '2024-03-28 07:57:10',
        updated_at: '2024-03-28 07:57:10',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [],
        media: [],
      },
      {
        id: 10,
        categories_name: 'Gynecol',
        status: '1',
        created_at: '2024-03-28 08:06:06',
        updated_at: '2024-03-28 08:06:06',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 35,
            model_type: 'App\\Models\\Category',
            model_id: 10,
            uuid: '8eef65d1-da9a-4af8-b4d1-4a4245da52c5',
            collection_name: 'category_categories_image',
            name: 'Covers-2',
            file_name: 'Covers-2.jpeg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 81873,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 22,
            created_at: '2024-03-28T08:04:48.000000Z',
            updated_at: '2024-03-28T08:06:06.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/35/Covers-2.jpeg',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/35/Covers-2.jpeg',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/35/conversions/Covers-2-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/35/conversions/Covers-2-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 35,
            model_type: 'App\\Models\\Category',
            model_id: 10,
            uuid: '8eef65d1-da9a-4af8-b4d1-4a4245da52c5',
            collection_name: 'category_categories_image',
            name: 'Covers-2',
            file_name: 'Covers-2.jpeg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 81873,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 22,
            created_at: '2024-03-28T08:04:48.000000Z',
            updated_at: '2024-03-28T08:06:06.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/35/Covers-2.jpeg',
            preview_url: '',
          },
        ],
      },
      {
        id: 11,
        categories_name: 'TestCategory',
        status: '1',
        created_at: '2024-03-28 08:26:52',
        updated_at: '2024-03-28 08:26:52',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 43,
            model_type: 'App\\Models\\Category',
            model_id: 11,
            uuid: '555c2f03-1f74-4976-a30f-21686fc56b45',
            collection_name: 'category_categories_image',
            name: 'dkfk',
            file_name: 'dkfk.jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 8373,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 29,
            created_at: '2024-03-28T08:26:41.000000Z',
            updated_at: '2024-03-28T08:26:52.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/43/dkfk.jpg',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/43/dkfk.jpg',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/43/conversions/dkfk-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/43/conversions/dkfk-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 43,
            model_type: 'App\\Models\\Category',
            model_id: 11,
            uuid: '555c2f03-1f74-4976-a30f-21686fc56b45',
            collection_name: 'category_categories_image',
            name: 'dkfk',
            file_name: 'dkfk.jpg',
            mime_type: 'image/jpeg',
            disk: 'public',
            conversions_disk: 'public',
            size: 8373,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 29,
            created_at: '2024-03-28T08:26:41.000000Z',
            updated_at: '2024-03-28T08:26:52.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/43/dkfk.jpg',
            preview_url: '',
          },
        ],
      },
      {
        id: 12,
        categories_name: 'Gynecologists',
        status: '1',
        created_at: '2024-03-28 10:20:20',
        updated_at: '2024-03-28 10:20:20',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 64,
            model_type: 'App\\Models\\Category',
            model_id: 12,
            uuid: 'bbf49a4d-0acc-43a7-b269-b83a9eae2312',
            collection_name: 'category_categories_image',
            name: '[FREE - HDconvert.com] dkfk',
            file_name: '[FREE---HDconvert.com]-dkfk.png',
            mime_type: 'image/png',
            disk: 'public',
            conversions_disk: 'public',
            size: 61404,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 49,
            created_at: '2024-03-28T10:20:06.000000Z',
            updated_at: '2024-03-28T10:20:20.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/64/[FREE---HDconvert.com]-dkfk.png',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/64/[FREE---HDconvert.com]-dkfk.png',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/64/conversions/[FREE---HDconvert.com]-dkfk-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/64/conversions/[FREE---HDconvert.com]-dkfk-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 64,
            model_type: 'App\\Models\\Category',
            model_id: 12,
            uuid: 'bbf49a4d-0acc-43a7-b269-b83a9eae2312',
            collection_name: 'category_categories_image',
            name: '[FREE - HDconvert.com] dkfk',
            file_name: '[FREE---HDconvert.com]-dkfk.png',
            mime_type: 'image/png',
            disk: 'public',
            conversions_disk: 'public',
            size: 61404,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 49,
            created_at: '2024-03-28T10:20:06.000000Z',
            updated_at: '2024-03-28T10:20:20.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/64/[FREE---HDconvert.com]-dkfk.png',
            preview_url: '',
          },
        ],
      },
      {
        id: 13,
        categories_name: 'Plastic and Reconstructive Surgeon',
        status: '1',
        created_at: '2024-03-28 10:21:29',
        updated_at: '2024-03-28 10:21:29',
        deleted_at: null,
        is_favorite: false,
        favorite_id: null,
        categories_image: [
          {
            id: 65,
            model_type: 'App\\Models\\Category',
            model_id: 13,
            uuid: '775acff1-2ff7-4c44-98d7-f01ea4ceb2d0',
            collection_name: 'category_categories_image',
            name: '[FREE - HDconvert.com] dkfk',
            file_name: '[FREE---HDconvert.com]-dkfk.png',
            mime_type: 'image/png',
            disk: 'public',
            conversions_disk: 'public',
            size: 61404,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 49,
            created_at: '2024-03-28T10:21:26.000000Z',
            updated_at: '2024-03-28T10:21:29.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/65/[FREE---HDconvert.com]-dkfk.png',
            preview_url: '',
            url: 'https://stimuli.craftsweb.co.in/storage/app/public/65/[FREE---HDconvert.com]-dkfk.png',
            thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/65/conversions/[FREE---HDconvert.com]-dkfk-thumbnail.jpg',
            preview_thumbnail:
              'https://stimuli.craftsweb.co.in/storage/app/public/65/conversions/[FREE---HDconvert.com]-dkfk-preview_thumbnail.jpg',
          },
        ],
        media: [
          {
            id: 65,
            model_type: 'App\\Models\\Category',
            model_id: 13,
            uuid: '775acff1-2ff7-4c44-98d7-f01ea4ceb2d0',
            collection_name: 'category_categories_image',
            name: '[FREE - HDconvert.com] dkfk',
            file_name: '[FREE---HDconvert.com]-dkfk.png',
            mime_type: 'image/png',
            disk: 'public',
            conversions_disk: 'public',
            size: 61404,
            manipulations: [],
            custom_properties: [],
            generated_conversions: {thumbnail: true, preview_thumbnail: true},
            responsive_images: [],
            order_column: 49,
            created_at: '2024-03-28T10:21:26.000000Z',
            updated_at: '2024-03-28T10:21:29.000000Z',
            original_url:
              'https://stimuli.craftsweb.co.in/storage/app/public/65/[FREE---HDconvert.com]-dkfk.png',
            preview_url: '',
          },
        ],
      },
      {
        id: 17,
        categories_name: 'खुद से प्यार',
        status: '1',
        created_at: '2024-05-01 07:06:26',
        updated_at: '2024-05-01 07:10:47',
        deleted_at: null,
        is_favorite: true,
        favorite_id: 26,
        categories_image: [],
        media: [],
      },
    ],
    affirmations: [],
  },
  message: 'Search results found successfully.',
  errors: [],
};
export default thisdata.data.categories;
