const affimations = {
  status: true,
  data: [
    {
      id: 1,
      affirmation_text:
        'I am a magnet for financial abundance, attracting wealth effortlessly into my life.',
      voice_one: [
        {
          id: 72,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: '6415e65b-af6b-435c-bb8f-04c4d31cda73',
          collection_name: 'affirmation_voice_one',
          name: 'blender',
          file_name: 'blender.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 1,
          created_at: '2024-04-12T11:35:47.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/72/blender.mp3',
          preview_url: '',
          url: 'https://stimuli.forebearpro.co.in/storage/app/public/72/blender.mp3',
        },
      ],
      voice_two: [
        {
          id: 73,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: '25bdb447-015e-459c-b2ef-372c0277152f',
          collection_name: 'affirmation_voice_two',
          name: 'circle',
          file_name: 'circle.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 2,
          created_at: '2024-04-12T11:35:49.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/73/circle.mp3',
          preview_url: '',
          url: 'https://stimuli.forebearpro.co.in/storage/app/public/73/circle.mp3',
        },
      ],
      voice_three: [
        {
          id: 74,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: '8458a69b-bc40-4484-a0b9-4c4fd91b9863',
          collection_name: 'affirmation_voice_three',
          name: 'blender',
          file_name: 'blender.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 3,
          created_at: '2024-04-12T11:35:53.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/74/blender.mp3',
          preview_url: '',
          url: 'https://stimuli.forebearpro.co.in/storage/app/public/74/blender.mp3',
        },
      ],
      voice_four: [
        {
          id: 75,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: 'd3bbad04-8a4b-45b6-91d5-1b486d17b32c',
          collection_name: 'affirmation_voice_four',
          name: 'circle',
          file_name: 'circle.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 4,
          created_at: '2024-04-12T11:35:57.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/75/circle.mp3',
          preview_url: '',
          url: 'https://stimuli.forebearpro.co.in/storage/app/public/75/circle.mp3',
        },
      ],
      status: '1',
      created_at: '2024-03-21 10:51:57',
      updated_at: '2024-03-21 10:56:17',
      deleted_at: null,
      is_favorite: true,
      favorite_id: 3,
      group: [
        {
          id: 8,
          group_name: 'Addctions',
          status: '1',
          created_at: '2024-03-21 10:49:33',
          updated_at: '2024-03-21 10:49:33',
          deleted_at: null,
          pivot: {
            affirmation_id: 1,
            group_id: 8,
          },
        },
      ],
      media: [
        {
          id: 72,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: '6415e65b-af6b-435c-bb8f-04c4d31cda73',
          collection_name: 'affirmation_voice_one',
          name: 'blender',
          file_name: 'blender.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 1,
          created_at: '2024-04-12T11:35:47.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/72/blender.mp3',
          preview_url: '',
        },
        {
          id: 73,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: '25bdb447-015e-459c-b2ef-372c0277152f',
          collection_name: 'affirmation_voice_two',
          name: 'circle',
          file_name: 'circle.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 2,
          created_at: '2024-04-12T11:35:49.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/73/circle.mp3',
          preview_url: '',
        },
        {
          id: 74,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: '8458a69b-bc40-4484-a0b9-4c4fd91b9863',
          collection_name: 'affirmation_voice_three',
          name: 'blender',
          file_name: 'blender.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 3,
          created_at: '2024-04-12T11:35:53.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/74/blender.mp3',
          preview_url: '',
        },
        {
          id: 75,
          model_type: 'App\\Models\\Affirmation',
          model_id: 1,
          uuid: 'd3bbad04-8a4b-45b6-91d5-1b486d17b32c',
          collection_name: 'affirmation_voice_four',
          name: 'circle',
          file_name: 'circle.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 16521,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 4,
          created_at: '2024-04-12T11:35:57.000000Z',
          updated_at: '2024-05-17T13:53:59.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/75/circle.mp3',
          preview_url: '',
        },
      ],
    },
    {
      id: 2,
      affirmation_text:
        'Every dollar I spend comes back to me multiplied in unexpected ways.',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-03-21 10:53:05',
      updated_at: '2024-03-21 10:56:34',
      deleted_at: null,
      is_favorite: true,
      favorite_id: 2,
      group: [
        {
          id: 1,
          group_name: 'Money Mastery ',
          status: '1',
          created_at: '2024-03-21 15:50:10',
          updated_at: '2024-03-21 10:23:26',
          deleted_at: null,
          pivot: {
            affirmation_id: 2,
            group_id: 1,
          },
        },
      ],
      media: [],
    },
    {
      id: 3,
      affirmation_text:
        'I am worthy of wealth and success, and I embrace abundance in all areas of my life.',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-03-21 10:53:36',
      updated_at: '2024-03-21 10:56:52',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 1,
          group_name: 'Money Mastery ',
          status: '1',
          created_at: '2024-03-21 15:50:10',
          updated_at: '2024-03-21 10:23:26',
          deleted_at: null,
          pivot: {
            affirmation_id: 3,
            group_id: 1,
          },
        },
      ],
      media: [],
    },
    {
      id: 4,
      affirmation_text:
        'Money flows to me easily and abundantly from multiple sources',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-03-21 10:54:14',
      updated_at: '2024-03-21 10:57:08',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 1,
          group_name: 'Money Mastery ',
          status: '1',
          created_at: '2024-03-21 15:50:10',
          updated_at: '2024-03-21 10:23:26',
          deleted_at: null,
          pivot: {
            affirmation_id: 4,
            group_id: 1,
          },
        },
      ],
      media: [],
    },
    {
      id: 5,
      affirmation_text:
        'I am financially free, living the life of my dreams with ease and joy.',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-03-21 10:57:44',
      updated_at: '2024-03-21 10:57:44',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 1,
          group_name: 'Money Mastery ',
          status: '1',
          created_at: '2024-03-21 15:50:10',
          updated_at: '2024-03-21 10:23:26',
          deleted_at: null,
          pivot: {
            affirmation_id: 5,
            group_id: 1,
          },
        },
      ],
      media: [],
    },
    {
      id: 6,
      affirmation_text: 'madditation',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-03-27 09:22:51',
      updated_at: '2024-03-27 09:22:51',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 4,
          group_name: 'Positive Thinking',
          status: '1',
          created_at: '2024-03-21 10:47:46',
          updated_at: '2024-03-21 10:47:46',
          deleted_at: null,
          pivot: {
            affirmation_id: 6,
            group_id: 4,
          },
        },
        {
          id: 5,
          group_name: 'Personal Growth',
          status: '1',
          created_at: '2024-03-21 10:48:10',
          updated_at: '2024-03-21 10:48:10',
          deleted_at: null,
          pivot: {
            affirmation_id: 6,
            group_id: 5,
          },
        },
        {
          id: 6,
          group_name: 'Family Life',
          status: '1',
          created_at: '2024-03-21 10:48:36',
          updated_at: '2024-03-21 10:48:36',
          deleted_at: null,
          pivot: {
            affirmation_id: 6,
            group_id: 6,
          },
        },
        {
          id: 7,
          group_name: 'Law Of Attraction',
          status: '1',
          created_at: '2024-03-21 10:49:11',
          updated_at: '2024-03-21 10:49:11',
          deleted_at: null,
          pivot: {
            affirmation_id: 6,
            group_id: 7,
          },
        },
        {
          id: 8,
          group_name: 'Addctions',
          status: '1',
          created_at: '2024-03-21 10:49:33',
          updated_at: '2024-03-21 10:49:33',
          deleted_at: null,
          pivot: {
            affirmation_id: 6,
            group_id: 8,
          },
        },
      ],
      media: [],
    },
    {
      id: 9,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-08 15:01:26',
      updated_at: '2024-04-08 15:01:26',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 9,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 10,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-08 15:02:10',
      updated_at: '2024-04-08 15:02:10',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 10,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 11,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-10 08:14:29',
      updated_at: '2024-04-10 08:14:29',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 11,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 12,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-11 07:42:54',
      updated_at: '2024-04-11 07:42:54',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 12,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 13,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-16 06:45:11',
      updated_at: '2024-04-16 06:45:11',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 13,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 14,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-16 10:00:20',
      updated_at: '2024-04-16 10:00:20',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 14,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 15,
      affirmation_text: 'i m checking',
      voice_one: [],
      voice_two: [],
      voice_three: [],
      voice_four: [],
      status: '1',
      created_at: '2024-04-18 12:24:49',
      updated_at: '2024-04-18 12:24:49',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 2,
          group_name: 'Sleep And Relaxation',
          status: '1',
          created_at: '2024-03-21 10:37:51',
          updated_at: '2024-03-21 10:37:51',
          deleted_at: null,
          pivot: {
            affirmation_id: 15,
            group_id: 2,
          },
        },
      ],
      media: [],
    },
    {
      id: 16,
      affirmation_text: 'मुझे खुद पर विश्वास है।',
      voice_one: [
        {
          id: 100,
          model_type: 'App\\Models\\Affirmation',
          model_id: 16,
          uuid: 'bc7db433-2f82-422b-95e1-e7fd7a843776',
          collection_name: 'affirmation_voice_one',
          name: '1714547844703qkqetrfg-voicemaker.in-speech',
          file_name: '1714547844703qkqetrfg-voicemaker.in-speech.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 58036,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 1,
          created_at: '2024-05-01T07:24:46.000000Z',
          updated_at: '2024-05-01T07:25:16.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/100/1714547844703qkqetrfg-voicemaker.in-speech.mp3',
          preview_url: '',
          url: 'https://stimuli.forebearpro.co.in/storage/app/public/100/1714547844703qkqetrfg-voicemaker.in-speech.mp3',
        },
      ],
      voice_two: [],
      voice_three: [
        {
          id: 101,
          model_type: 'App\\Models\\Affirmation',
          model_id: 16,
          uuid: '25279140-37a8-42cb-850c-c346df5fd7cc',
          collection_name: 'affirmation_voice_three',
          name: 'मुझे खुद पर विश्वास ',
          file_name: 'मुझे-खुद-पर-विश्वास-.m4a',
          mime_type: 'audio/x-m4a',
          disk: 'public',
          conversions_disk: 'public',
          size: 25293,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 2,
          created_at: '2024-05-01T07:25:13.000000Z',
          updated_at: '2024-05-01T07:25:16.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/101/मुझे-खुद-पर-विश्वास-.m4a',
          preview_url: '',
          url: 'https://stimuli.forebearpro.co.in/storage/app/public/101/मुझे-खुद-पर-विश्वास-.m4a',
        },
      ],
      voice_four: [],
      status: '1',
      created_at: '2024-05-01 07:25:16',
      updated_at: '2024-05-01 07:25:16',
      deleted_at: null,
      is_favorite: false,
      favorite_id: null,
      group: [
        {
          id: 5,
          group_name: 'Personal Growth',
          status: '1',
          created_at: '2024-03-21 10:48:10',
          updated_at: '2024-03-21 10:48:10',
          deleted_at: null,
          pivot: {
            affirmation_id: 16,
            group_id: 5,
          },
        },
      ],
      media: [
        {
          id: 100,
          model_type: 'App\\Models\\Affirmation',
          model_id: 16,
          uuid: 'bc7db433-2f82-422b-95e1-e7fd7a843776',
          collection_name: 'affirmation_voice_one',
          name: '1714547844703qkqetrfg-voicemaker.in-speech',
          file_name: '1714547844703qkqetrfg-voicemaker.in-speech.mp3',
          mime_type: 'audio/mpeg',
          disk: 'public',
          conversions_disk: 'public',
          size: 58036,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 1,
          created_at: '2024-05-01T07:24:46.000000Z',
          updated_at: '2024-05-01T07:25:16.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/100/1714547844703qkqetrfg-voicemaker.in-speech.mp3',
          preview_url: '',
        },
        {
          id: 101,
          model_type: 'App\\Models\\Affirmation',
          model_id: 16,
          uuid: '25279140-37a8-42cb-850c-c346df5fd7cc',
          collection_name: 'affirmation_voice_three',
          name: 'मुझे खुद पर विश्वास ',
          file_name: 'मुझे-खुद-पर-विश्वास-.m4a',
          mime_type: 'audio/x-m4a',
          disk: 'public',
          conversions_disk: 'public',
          size: 25293,
          manipulations: [],
          custom_properties: [],
          generated_conversions: [],
          responsive_images: [],
          order_column: 2,
          created_at: '2024-05-01T07:25:13.000000Z',
          updated_at: '2024-05-01T07:25:16.000000Z',
          original_url:
            'https://stimuli.forebearpro.co.in/storage/app/public/101/मुझे-खुद-पर-विश्वास-.m4a',
          preview_url: '',
        },
      ],
    },
  ],
  message: 'All Affirmation are fetched successfully..',
  errors: [],
};
export default affimations.data;
